name: Build nixrs Examples
on: [push, pull_request, workflow_dispatch]
jobs:
   build-examples:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: cachix/install-nix-action@v31
           with:
              extra_nix_config: "experimental-features = "
              nix_path: nixpkgs=$HOME/.nix-defexpr/channels/nixos
         - run: nix-channel --add https://nixos.org/channels/nixos-unstable-small nixos
         - run: nix-channel --update
         - run: nix-env --install --file install.nix
         - working-directory: examples
           run: |
              for example in *; do
                  cd $example
                  nixrs b
                  cd ..
              done
