name: Build nixrs Examples
on: [push, pull_request, workflow_dispatch]
jobs:
   build-examples:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: cachix/install-nix-action@v31
           with:
              nix_path: nixpkgs=channel:nixos-unstable
         - run: nix-env --install --file install.nix
         - working-directory: examples
           run: |
              for example in *; do
                  cd $example
                  nixrs b
                  cd ..
              done
