name: nixrs tests
on: [push, pull_request, workflow_dispatch]
jobs:
   nixty-tests:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: cachix/install-nix-action@v31
           with:
              extra_nix_config: "experimental-features = nix-command"
         - run: nix eval -f nixty/test.nix
   build-examples:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: cachix/install-nix-action@v31
           with:
              extra_nix_config: "experimental-features = "
              nix_path: nixpkgs=/home/runner/.nix-defexpr/channels/nixos
         - run: nix-channel --add https://nixos.org/channels/nixos-unstable-small nixos
         - run: nix-channel --update
         - working-directory: examples
           run: |
              for example in *; do
                if [ ! -d $example ]; then
                  continue;
                fi
                case "$example" in
                  "cratesio-dep" | "workspace")
                    echo "Found blacklisted test, skipping"
                  ;;
                  *)
                    cd $example
                    ../../bin/nixrs b
                    cd ..
                  ;;
                esac
              done
